'use client'

export const dynamic = 'force-dynamic'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/client'
import { Search, LogOut, ArrowUpRight } from 'lucide-react'

type Request = { id:string; request_code:string; title:string; requester_name:string; requester_email:string; request_type:string; urgency:string; priority:string; status:string; created_at:string; desired_deadline:string|null }
const statuses=['All','New','Reviewing','Planned','In Progress','Blocked','Done','Rejected']; const priorities=['All','P0','P1','P2','P3']; const types=['All','bug','feature','improvement','data_reporting','content_admin','other']; const urgencies=['All','blocking','high','normal','low']
export default function TechPage(){ const [supabase,setSupabase]=useState<ReturnType<typeof createClient>|null>(null); const [user,setUser]=useState<any>(null); const [requests,setRequests]=useState<Request[]>([]); const [loading,setLoading]=useState(true); const [login,setLogin]=useState({email:'',password:''}); const [error,setError]=useState(''); const [filters,setFilters]=useState({search:'',status:'All',priority:'All',type:'All',urgency:'All',date:'',sort:'newest'}); const [refresh,setRefresh]=useState(0)
 useEffect(()=>{setSupabase(createClient())},[]); useEffect(()=>{if(!supabase)return; supabase.auth.getUser().then(({data})=>{setUser(data.user);setLoading(false)}); const {data}=supabase.auth.onAuthStateChange((_e,session)=>setUser(session?.user??null)); return()=>data.subscription.unsubscribe()},[supabase])
 useEffect(()=>{if(!user)return; supabase.from('tech_requests').select('id,request_code,title,requester_name,requester_email,request_type,urgency,priority,status,created_at,desired_deadline').order('created_at',{ascending:false}).then(({data,error})=>{if(error)setError('Could not load requests.');setRequests((data??[]) as Request[])})},[supabase,user,refresh])
 async function signIn(e:React.FormEvent){e.preventDefault();if(!supabase)return;setError('');const {error}=await supabase.auth.signInWithPassword(login);if(error)setError('Invalid email or password.')} if(loading)return <div className="center-state">Loading workspace…</div>; if(!user)return <main className="auth-page"><form className="auth-card" onSubmit={signIn}><div className="brand"><div className="brand-mark">M</div><span>maargh<span className="brand-dot">.</span></span></div><h1>Tech workspace</h1><p>Sign in to manage technology requests.</p><input required type="email" placeholder="Email" value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/><input required type="password" placeholder="Password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/>{error&&<p className="form-error">{error}</p>}<button className="primary-button">Sign in</button></form></main>
 const filtered=requests.filter(r=>(!filters.search||`${r.title} ${r.request_code} ${r.requester_name}`.toLowerCase().includes(filters.search.toLowerCase()))&&(filters.status==='All'||r.status===filters.status)&&(filters.priority==='All'||r.priority===filters.priority)&&(filters.type==='All'||r.request_type===filters.type)&&(filters.urgency==='All'||r.urgency===filters.urgency)&&(!filters.date||r.created_at.startsWith(filters.date))).sort((a,b)=>filters.sort==='oldest'?a.created_at.localeCompare(b.created_at):a.title.localeCompare(b.title))
 const open=requests.filter(r=>!['Done','Rejected'].includes(r.status)).length, inProgress=requests.filter(r=>r.status==='In Progress').length, done=requests.filter(r=>r.status==='Done').length
 return <main className="tech-page"><header className="tech-header"><div className="brand"><div className="brand-mark">M</div><span>maargh<span className="brand-dot">.</span></span></div><div><span className="eyebrow">Internal workspace</span><h1>Technology requests</h1></div><button className="icon-button" onClick={()=>supabase.auth.signOut()} aria-label="Sign out"><LogOut size={17}/></button></header><div className="tech-content"><div className="metric-grid"><Metric label="Open requests" value={open}/><Metric label="In progress" value={inProgress}/><Metric label="Completed" value={done}/><Metric label="Total requests" value={requests.length}/></div><section className="panel all-requests"><div className="panel-heading"><div><h2>All requests</h2><p>{requests.length ? `${filtered.length} of ${requests.length} requests` : 'No requests yet.'}</p></div><Link className="text-button" href="/request">Public request form <ArrowUpRight size={14}/></Link></div><div className="filters"><label className="search-box"><Search size={16}/><input placeholder="Search requests" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></label><select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}>{statuses.map(x=><option key={x}>{x}</option>)}</select><select value={filters.priority} onChange={e=>setFilters({...filters,priority:e.target.value})}>{priorities.map(x=><option key={x}>{x}</option>)}</select><select value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}>{types.map(x=><option key={x}>{x}</option>)}</select><select value={filters.urgency} onChange={e=>setFilters({...filters,urgency:e.target.value})}>{urgencies.map(x=><option key={x}>{x}</option>)}</select><input type="date" value={filters.date} onChange={e=>setFilters({...filters,date:e.target.value})}/><select value={filters.sort} onChange={e=>setFilters({...filters,sort:e.target.value})}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="title">Title A–Z</option></select></div>{error&&<p className="form-error">{error} <button onClick={()=>setRefresh(refresh+1)}>Retry</button></p>}<div className="request-table"><div className="table-header"><span>Request</span><span>Status</span><span>Priority</span><span>Submitted</span></div>{filtered.map(r=><Link href={`/tech/requests/${r.id}`} className="request-row" key={r.id}><div className="request-main"><div className="request-file">{r.request_code}</div><div><strong>{r.title}</strong><span>{r.requester_name} · {r.request_type} · {r.urgency}</span></div></div><span className={`status ${r.status.toLowerCase().replace(' ','-')}`}><i/>{r.status}</span><span className={`priority ${r.priority.toLowerCase()}`}>{r.priority}</span><span className="request-date">{new Date(r.created_at).toLocaleDateString()}</span></Link>)}{!filtered.length&&<div className="empty-state">No requests yet.</div>}</div></section></div></main> }
function Metric({label,value}:{label:string;value:number}){return <div className="stat-card"><span className="stat-label">{label}</span><strong>{value}</strong><span className="stat-note">From Supabase</span></div>}
